name: Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
 
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.3

      - name: Install dependencies
        run: bun install
          
      - name: Build
        run: bun run build

      - name: Add additional files to build directory
        run: cp -rT ./misc ./build/__misc
        
      - name: Upload Build
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: build/
          remote_path: /var/www/hivey/frontend
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
        
      - name: Update systemd service
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: sudo /var/www/hivey/frontend/__misc/scripts/update-systemd-service.sh
          
